version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: ziltag_development
    volumes:
      - pgdata:/var/lib/postgresql/data
  front:
    image: ziltag/frontend-ziltag.com:latest
    command: npm run serve
    ports:
      - "${PORT}:2000"
      - "${SSL_PORT}:2001"
      - "${DEBUG_PORT}:1999"
    volumes:
      - ./env.js:/usr/src/app/env.js
    depends_on:
      - app
  app:
    build: .
    image: ziltag
    volumes:
      - .:/ziltag
      - node_modules:/ziltag/node_modules
    depends_on:
      - db
volumes:
  pgdata:
  node_modules:
