version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: ziltag_development
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    image: ziltag
    volumes:
      - .:/ziltag
      - node_modules:/ziltag/node_modules
    ports:
      - 3000:3000
      - 3310:3310
    depends_on:
      - db
volumes:
  pgdata:
  node_modules:
