version: '2'
services:
  db:
    image: postgres:9.4
    environment:
      POSTGRES_DB: ziltag_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ziltag
  app:
    build: .
    image: ziltag
    volumes:
      - .:/ziltag
      - node_modules:/ziltag/node_modules
    depends_on:
      - db
    networks:
      - ziltag
  web:
    image: ziltag
    command: bundle exec puma
    volumes_from:
      - app
    depends_on:
      - app
    networks:
      - ziltag
  sse:
    image: ziltag
    command: ruby lib/sse.rb -svp 3310 --ssl --ssl-key ../config/ssl/localhost.key --ssl-cert ../config/ssl/localhost.crt -c ./sse/config.rb
    volumes_from:
      - app
    depends_on:
      - app
    networks:
      - ziltag
  worker:
    image: ziltag
    command: bundle exec rake qc:work
    environment:
      QUEUES: "mailers,default"
      QC_MEASURE: "true"
    volumes_from:
      - app
    depends_on:
      - app
    networks:
      - ziltag
  webpack:
    image: ziltag
    command: npm run dev
    volumes_from:
      - app
    depends_on:
      - app

volumes:
  pgdata:
  node_modules:

networks:
  ziltag:
    external: true
