default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: ziltag_development
test:
  <<: *default
  database: ziltag_test
production:
  <<: *default
  database: ziltag
  username: deploy
  password: <%= ENV['ZILTAG_DATABASE_PASSWORD'] %>
