default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: ziltag_development
  pool: 5
  username: postgres
  password:
  host: db
test:
  <<: *default
  database: ziltag_test
  pool: 5
  username: postgres
  password:
  host: db_test
